name: Release

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: "0"
      - name: Use .NET 8.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Use .NET 9.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Use .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Run QA
        run: make qa
      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.7.1
      - name: Create new version
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          git tag v${{steps.get_next_version.outputs.version}}
          git push origin v${{steps.get_next_version.outputs.version}}
      - name: Build artifacts
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          make build
      - name: Publish new version
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          dotnet nuget push ./build/*.nupkg \
            --api-key ${{ secrets.TOKEN_GITHUB_TO_NUGET_RW }} \
            --source https://api.nuget.org/v3/index.json
